version: '3.8'
services:
  git-sync:
    image: registry.k8s.io/git-sync/git-sync:v4.1.0
    environment:
      - GITSYNC_REPO=git@github.com:tuancamtbtx/airflow-on-k8s.git
      - GITSYNC_BRANCH=master
      - GITSYNC_DEST=/git
      - GITSYNC_WAIT=300  # Time in seconds between syncs
      - GITSYNC_SSH=1
      - GITSYNC_SSH_KEY_FILE=/tmp/.ssh/id_rsa.pub
      - GITSYNC_SSH_KNOWN_HOSTS_FILE=/tmp/.ssh/known_hosts
    volumes:
      - ./airflow_dags/dags:/git
      - ./private/id_rsa.pub:/tmp/.ssh/id_rsa.pub
      - ./private/known_hosts:/tmp/.ssh/known_hosts
