executor: "KubernetesExecutor"
images: 
  airflow: "apache/airflow:2.0.1-python3.8"
  pullPolicy: "IfNotPresent"
  

dags:
  gitSync:
      enabled: true
      repo: git@github.com:tuancamtbtx/airflow-example.git
      branch: master
      subPath: "airflow/dags"
      sshKeySecret: airflow-ssh-secret